# Generated by Django 3.2.9 on 2021-12-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='cwv'),
        ),
    ]
