# Generated by Django 3.2.9 on 2021-12-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Hair', 'Hair'), ('Nails', 'Nails'), ('Makeup', 'Makeup'), ('Body', 'Body')], max_length=100),
        ),
    ]
