# Generated by Django 3.2.9 on 2021-12-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='customer',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='beauty.person'),
        ),
    ]
